---
- name: Example Playbook
  hosts: all
  become: yes
  tasks:
    - name: Update entry into /tmp/textfile.txt 20230113
      lineinfile:
        path: /tmp/report/textfile.txt
        line: 'nameserver 10.1.250.10'
      register: file_created

    - name: Print debug message -> textfile.txt modify
      debug:
        var: file_created
    
    - name: Print debug -> inventory_hostname
      debug:
        msg: "System: {{ inventory_hostname }}"

    - name: Add a variable user and variable primary group
      ansible.builtin.user:
        name: "{{ user_name }}"
        group: "{{ group_name }}"

    - name: Show content of /var/log/secure
      command: 'tail /var/log/secure'
      register: cat1
    
    - name: Print debug message -> cat1
      debug:
        var: cat1
    
    - name: cat /etc/redhat-release
      command: 'cat /etc/redhat-release'
      register: cat2
    
    - name: Print debug message -> cat2
      debug:
        var: cat2
