---
- name: Copy file to the same Windows host
  hosts: all
  gather_facts: no

  vars:
    source_path: "d:\\_win10_tricks.diz"
    dest_path: "d:\\_win10_tricksx.diz"

  tasks:
    - name: Copy file
      win_copy:
        src: "{{ source_path }}"
        dest: "{{ dest_path }}"
        #force: yes
