---
- name: Copy file to the same Windows host
  hosts: windows_host
  gather_facts: no

  vars:
    source_path: "d:\\_download\\_history.diz"
    dest_path: "d:\\temp\\x\\x\\_history.diz"
    
  tasks:
    - name: Copy file
      win_copy:
        src: "{{ source_path }}"
        dest: "{{ dest_path }}"
