---
- name: Copy file to the same Windows host
  hosts: all
  gather_facts: no

  tasks:
    - name: Copy file
      template:
        src: d:\_download\_history.diz
        dest: d:\temp\x\x\_history.diz
        #force: yes
